services:
  - type: web
    name: vuk-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: NODE_OPTIONS=--max-old-space-size=460 npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
